name: Trigger auto deployment for meals-back

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/meals-back-AutoDeployTrigger-e4c2383c-6d5b-4e69-8528-2a54904ec28a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MEALSBACK_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MEALSBACK_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MEALSBACK_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.MEALSBACK_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MEALSBACK_REGISTRY_PASSWORD }}
          containerAppName: meals-back
          resourceGroup: meals-group
          imageToBuild: ghcr.io/meals-back:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


